# IP1
## Evan Gousha
### Spring 2022

a.

In [2]:
import numpy as np

In [2]:
arr1=np.array([[10,20],[30,40]])
print(arr1)

[[10 20]
 [30 40]]


In [4]:
np.square(arr1)

array([[ 100,  400],
       [ 900, 1600]], dtype=int32)

In [8]:
for x in arr1:
    x=x+100
    print(x)

[110 120]
[130 140]


In [9]:
for x in arr1:
    x=x*5
    print(x)

[ 50 100]
[150 200]


In [10]:
np.sqrt(arr1)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

b.

In [20]:
arr2=np.arange(3,28,3)
arr2.reshape(3,3)

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [19]:
arr3=np.linspace(1,10,9)
arr3.reshape(3,3)

array([[ 1.   ,  2.125,  3.25 ],
       [ 4.375,  5.5  ,  6.625],
       [ 7.75 ,  8.875, 10.   ]])

In [22]:
arr4=np.multiply(arr2,arr3)
arr4.reshape(3,3)

array([[  3.  ,  12.75,  29.25],
       [ 52.5 ,  82.5 , 119.25],
       [162.75, 213.  , 270.  ]])

c.

In [4]:
process1=np.load('process1.npy')
process2=np.load('process2.npy')
process3=np.load('process3.npy')
process4=np.load('process4.npy')
process5=np.load('process5.npy')

In [9]:
stack=np.vstack((process1,process2,process3,process4,process5))
print(stack)

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]


In [10]:
stack.mean(axis=0)

array([72. , 27.8, 45.6, 12. , 47.8])